### ISSUE TITLE
Gameboy has issue in top left corner of scanlines

### ISSUE THREAD

**Issue by israelperez** [biscuits99/rp-video-manager#1] opened 2015-10-18 03:41 UTC
If you take a look at the scanlines that cover the game the top lefthand corner is different to the rest of the scan lines. You can see this if you zoom out and maybe use a black layer behind the image

**Comment by biscuits99** [comment] 2015-10-18 14:10
Which menu setting was used to apply this change?

**Comment by israelperez** [comment] 2015-10-18 21:19
this in the overlay artwork png file itself. the over lay contains the scanlines

**Comment by biscuits99** [comment] 2015-10-18 22:12
The overlay images are made by individual users (depending on which menu item you choose), so not a bug per se. I'll close this one for the moment.

**Closed as completed by biscuits99** 2015-10-18 22:12 UTC
